### ISSUE TITLE
feature selection on zip

### ISSUE THREAD

**Issue by yujincheng08** [matzefriedrich/zip-extensions-rs#16]
Now we always use the default features of zip. Can feature selection be added?

**Comment by matzefriedrich** [comment]
Thank you for your suggestion regarding the zip feature selection; it sounds doable, and I want to encourage you to implement the feature and submit a pull request. I will happily integrate it into the project.

**Comment by yujincheng08** [comment]
@matzefriedrich https://github.com/matzefriedrich/zip-extensions-rs/pull/17

**Comment by matzefriedrich** [comment]
@yujincheng08 There is a new release with the requested feature https://github.com/matzefriedrich/zip-extensions-rs/releases/tag/v0.8.1
