### ISSUE TITLE
Include target directory name in path hierarchy

### ISSUE THREAD

**Issue by lebe-dev** [matzefriedrich/zip-extensions-rs#8]
Hello.

Crate provides very convenient function `create_from_directory`, but how to include target folder name in zip hierarchy?

For example, i have path `c:\media` with folders: `dvd1`, `dvd2`, `dvdN`.

I want to create zip for `dvd1` with paths:
- `dvd1\some\file.jpg`
- `dvd1\some\sub2\fish.jpg`

Is is it possible?

p. s: Thanks for your crate it really helps :)

**Comment by matzefriedrich** [comment]
The convenience function `create_from_directory` expects a single directory path expression, traverses the hierarchy, and adds all files and subfolders to the archive (you can find an example in the README file).

To create a zip archive for `dvd1`, you´d pass its full directory path (which would be `c:\media\dvd1` in that case) to the `create_from_directory` method. The current implementation does not allow any filtering; it will just grab everything within the specified directory and add it to the archive.

**Comment by lebe-dev** [comment]
I've implemented what i wanted but too shy to make PR and not so confident in my implementation (code quality) :))

https://github.com/matzefriedrich/zip-extensions-rs/commit/261bb711b87340f1cab926a3afc022831420900c

I've posted this commit here just to explain original idea. Yes i know that 'bool' as func argument is anti-pattern, but i don't know how to make it better.

**Comment by matzefriedrich** [comment]
No worries, sir; I can see your intentions. It is true the boolean parameter could be solved better; maybe it should just go into the `FileOptions` structure. I will take a close look at this.
